[project]
name = "odoo-addons-oca-product-pack"
version = "18.0.20250114.0"
dependencies = [
    "odoo-addon-product_pack==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
